
pbp_map = {
    'home_team': 'first',
    'away_team': 'first',
    'location': 'first',
    'season_type': 'first',
    'defteam': 'first',
    'game_date': 'first',
    'ydstogo': 'mean',
    'ydsnet': 'mean',
    'yards_gained': 'mean',
    # 'yards_after_catch': ['mean', 'sum']
    'first_down': 'sum',
    'first_down_rush': 'sum',
    'first_down_pass': 'sum',
    'third_down_converted': 'sum',
    'third_down_failed': 'sum',
    'fourth_down_converted': 'sum',
    'fourth_down_failed': 'sum',
    'incomplete_pass': 'sum',
    'interception': 'sum',
    'punt_inside_twenty': 'sum',
    'punt_in_endzone': 'sum',
    'kickoff_inside_twenty': 'sum',
    'kickoff_in_endzone': 'sum',
    'penalty': 'sum',
    'fumble': 'sum',
    'fumble_lost': 'sum',
    'qb_hit': 'sum',
    'rush_attempt': 'sum',
    'pass_attempt': 'sum',
    'sack': 'sum',
    'touchdown': 'sum',
    'pass_touchdown': 'sum',
    'rush_touchdown': 'sum',
    'two_point_attempt': 'sum',
    'field_goal_attempt': 'sum',
    'two_point_conv_result': 'sum',
    'complete_pass': 'sum',
    'passing_yards': 'sum',
    'rushing_yards': 'sum',
    'return_yards': 'sum',
    'penalty_yards': 'sum',
    'cp': 'mean',
    'away_score': 'last',
    'home_score': 'last',
    'result': 'last',
    'total': 'last',
    'spread_line': 'last',
    'total_line': 'last',
    'div_game': 'max',
    'roof': 'first',
    'surface': 'first',
    'temp': 'mean',
    'wind': 'mean',
    'home_opening_kickoff': 'max'


}